import { pt } from './utils/convertDistance';

const useBF = true;
const STROKE_WIDTH = useBF ? 0.75 : pt(0.25, 'mm');

export const Settings = {
	ARMOR_RATING_TANK_HEIGHT: pt(5.3, 'mm'),
	ARMOR_RATING_MISC_HEIGHT: pt(7, 'mm'),
	ARMOR_RATING_FONT_SIZE: 12,
	CARD_HEIGHT: pt(80, 'mm'),
	CARD_MARGINS: pt(5, 'mm'),
	CARD_WIDTH: pt(110, 'mm'),
	CORNER_RADIUS: pt(1, 'mm'),
	STAT_BLOCK_WIDTH: pt(23, 'mm'),
	STAT_BLOCK_HEADER_HEIGHT: pt(1.9, 'mm'),
	STAT_HEADER_FONT_SIZE: 4,
	STAT_BLOCK_INNER_MARGIN: pt(0.5, 'mm'),
	BLOCK_MARGIN: pt(1.65, 'mm'),
	SOFT_STAT_PRIMARY_RATING_BACKGROUND_COLOR: '#D2232A',
	SOFT_STAT_PRIMARY_RATING_FONT_SIZE: 8,
	SOFT_STAT_PRIMARY_RATING_HEIGHT: useBF ? pt(3.055, 'mm') + STROKE_WIDTH : pt(3.3, 'mm'),
	SOFT_STAT_SECONDARY_RATING_BACKGROUND_COLOR: '#FFFFFF',
	SOFT_STAT_SECONDARY_RATING_HEIGHT: pt(4.2, 'mm'),
	SOFT_STAT_SECONDARY_RATING_NAME_FONT_SIZE: 5,
	SOFT_STAT_SECONDARY_RATING_ATTRIBUTE_FONT_SIZE: 6,
	STROKE_WIDTH,
};
